projects:

  fierry:
    main:   source/app.coffee
    source: source

  fierry-pfc:
    main:   performance/app.coffee
    source: performance
    dependences:
      - fierry
      - [fest, ../quality]
